# aaa_button_order.tcl - Плагин управления порядком кнопок

namespace eval ::plugin::button_order {
    variable config_file ""

    proc init {} {
        variable config_file
        set script_path [file normalize [info script]]
        set config_file [file join [file dirname $script_path] "button_order.cfg"]

        load_config

        after idle ::plugin::button_order::scan_and_apply

        ::core::register_plugin_button "btnorder" "⚙ Порядок" ::plugin::button_order::show_dialog
        return 1
    }

    proc scan_and_apply {} {
        variable order
        variable saved_order
        variable hidden
        array unset order
        set idx 0
        foreach child [winfo children .toolbar.plugins] {
            set name ""
            regexp {btn_(.+)} $child -> name
            if {$name ne ""} {
                if {[info exists saved_order($name)]} {
                    set order($name) $saved_order($name)
                } else {
                    set order($name) $idx
                    incr idx
                }
                set txt [$child cget -text]
                set ::plugin::button_order::button_label($name) $txt
            }
        }
        apply_order
    }

    proc apply_order {} {
        variable order
        variable hidden
        if {![array exists order]} return
        set pairs {}
        foreach {name ord} [array get order] {
            if {$name eq "btnorder"} continue
            lappend pairs [list $name $ord]
        }
        set sorted [lsort -integer -index 1 $pairs]
        set children [winfo children .toolbar.plugins]
        foreach c $children { pack forget $c }
        foreach pair $sorted {
            lassign $pair name ord
            if {[info exists hidden($name)] && $hidden($name)} continue
            set btn ".toolbar.plugins.btn_$name"
            if {[winfo exists $btn]} {
                pack $btn -side left -padx 2
            }
        }
        set btn ".toolbar.plugins.btn_btnorder"
        if {[winfo exists $btn]} {
            pack $btn -side left -padx 2
        }
    }

    proc load_config {} {
        variable config_file
        if {[file exists $config_file]} {
            source $config_file
        }
    }

    proc save_config {} {
        variable config_file
        variable order
        variable hidden
        set f [open $config_file w]
        puts $f "# auto-generated by button_order plugin"
        puts $f "array set ::plugin::button_order::saved_order {"
        set pairs {}
        foreach {name ord} [array get order] { lappend pairs [list $name $ord] }
        foreach pair [lsort -integer -index 1 $pairs] {
            lassign $pair name ord
            puts $f "    {$name} {$ord}"
        }
        puts $f "}"
        if {[array exists hidden] && [array size hidden] > 0} {
            puts $f "array set ::plugin::button_order::hidden {"
            foreach {name val} [array get hidden] {
                puts $f "    {$name} {$val}"
            }
            puts $f "}"
        }
        close $f
    }

    proc get_sorted_buttons {} {
        variable order
        if {![array exists order]} { return {} }
        set pairs {}
        foreach {name ord} [array get order] { lappend pairs [list $name $ord] }
        set result {}
        foreach pair [lsort -integer -index 1 $pairs] {
            lassign $pair name ord
            if {$name eq "btnorder"} continue
            lappend result $name
        }
        lappend result "btnorder"
        return $result
    }

    proc show_dialog {} {
        if {[winfo exists .btnorder_dlg]} { destroy .btnorder_dlg }

        set bg "#2D2D2D"
        set fg "#CCCCCC"
        set selbg "#264F78"
        if {[info exists ::core::config(theme)] && $::core::config(theme) ne "dark"} {
            set bg "#FFFFFF"
            set fg "#000000"
            set selbg "#0078D7"
        }

        if {$bg eq "#FFFFFF"} {
            set fg_btn "#000000"
            set bg_btn "#F0F0F0"
        } else {
            set fg_btn "#FFFFFF"
            set bg_btn "#404040"
        }
        set warn_bg "#5C2E2E"

        toplevel .btnorder_dlg -background $bg
        wm title .btnorder_dlg "Порядок кнопок"
        wm transient .btnorder_dlg .
        wm resizable .btnorder_dlg 0 0

        frame .btnorder_dlg.top -background $bg
        label .btnorder_dlg.top.title -text "Кнопки на панели" -font {TkFixedFont 11 bold} \
            -background $bg -foreground $fg
        pack .btnorder_dlg.top.title -pady 5
        pack .btnorder_dlg.top -fill x

        frame .btnorder_dlg.main -background $bg
        listbox .btnorder_dlg.main.list -width 28 -height 12 -font {TkFixedFont 10} \
            -background $bg -foreground $fg -selectbackground $selbg \
            -selectforeground "#FFFFFF" -borderwidth 1 -relief solid \
            -activestyle none -exportselection 0
        scrollbar .btnorder_dlg.main.scroll -command {.btnorder_dlg.main.list yview}
        .btnorder_dlg.main.list configure -yscrollcommand {.btnorder_dlg.main.scroll set}
        pack .btnorder_dlg.main.scroll -side right -fill y
        pack .btnorder_dlg.main.list -side left -fill both -expand 1 -padx {10 0}
        pack .btnorder_dlg.main -pady 5 -padx 10

        refresh_list
        .btnorder_dlg.main.list selection set 0

        frame .btnorder_dlg.ctrl -background $bg
        button .btnorder_dlg.ctrl.up -text "▲ Вверх" -width 12 \
            -command {::plugin::button_order::move_up} \
            -background $bg_btn -foreground $fg_btn -relief raised
        button .btnorder_dlg.ctrl.down -text "▼ Вниз" -width 12 \
            -command {::plugin::button_order::move_down} \
            -background $bg_btn -foreground $fg_btn -relief raised
        button .btnorder_dlg.ctrl.hide -text "👁 Скрыть" -width 12 \
            -command {::plugin::button_order::toggle_hide} \
            -background $bg_btn -foreground $fg_btn -relief raised
        pack .btnorder_dlg.ctrl.up .btnorder_dlg.ctrl.down .btnorder_dlg.ctrl.hide \
            -side left -padx 4 -pady 5
        pack .btnorder_dlg.ctrl -pady 5

        frame .btnorder_dlg.bottom -background $bg
        button .btnorder_dlg.bottom.save -text "💾 Запомнить" -width 14 \
            -command {::plugin::button_order::do_save} \
            -background $bg_btn -foreground $fg_btn -relief raised
        button .btnorder_dlg.bottom.close -text "✕ Закрыть" -width 14 \
            -command {destroy .btnorder_dlg} \
            -background $bg_btn -foreground $fg_btn -relief raised
        pack .btnorder_dlg.bottom.save .btnorder_dlg.bottom.close -side left -padx 5 -pady 5
        pack .btnorder_dlg.bottom -pady {0 10}

        update idletasks
        set x [expr {[winfo rootx .] + [winfo width .] / 2 - [winfo reqwidth .btnorder_dlg] / 2}]
        set y [expr {[winfo rooty .] + [winfo height .] / 2 - [winfo reqheight .btnorder_dlg] / 2}]
        wm geometry .btnorder_dlg +${x}+${y}
        raise .btnorder_dlg
        grab .btnorder_dlg
    }

    proc get_selected_name {} {
        set sel [.btnorder_dlg.main.list curselection]
        if {$sel eq ""} { return "" }
        set names [get_sorted_buttons]
        if {$sel < [llength $names]} {
            return [lindex $names $sel]
        }
        return ""
    }

    proc move_up {} {
        variable order
        set name [get_selected_name]
        if {$name eq "" || $name eq "btnorder"} return
        set cur_order $order($name)

        set pairs {}
        foreach {n o} [array get order] { if {$n ne "btnorder"} { lappend pairs [list $n $o] } }
        set sorted [lsort -integer -index 1 $pairs]
        set names {}
        foreach pair $sorted { lappend names [lindex $pair 0] }

        set idx [lsearch $names $name]
        if {$idx <= 0} return
        set prev_name [lindex $names [expr {$idx - 1}]]

        set prev_order $order($prev_name)
        set order($name) $prev_order
        set order($prev_name) $cur_order

        apply_order
        refresh_list
        .btnorder_dlg.main.list selection clear 0 end
        .btnorder_dlg.main.list selection set [expr {$idx - 1}]
    }

    proc move_down {} {
        variable order
        set name [get_selected_name]
        if {$name eq "" || $name eq "btnorder"} return
        set cur_order $order($name)

        set pairs {}
        foreach {n o} [array get order] { if {$n ne "btnorder"} { lappend pairs [list $n $o] } }
        set sorted [lsort -integer -index 1 $pairs]
        set names {}
        foreach pair $sorted { lappend names [lindex $pair 0] }

        set idx [lsearch $names $name]
        if {$idx >= [expr {[llength $names] - 1}]} return
        set next_name [lindex $names [expr {$idx + 1}]]

        set next_order $order($next_name)
        set order($name) $next_order
        set order($next_name) $cur_order

        apply_order
        refresh_list
        .btnorder_dlg.main.list selection clear 0 end
        .btnorder_dlg.main.list selection set [expr {$idx + 1}]
    }

    proc toggle_hide {} {
        variable hidden
        set name [get_selected_name]
        if {$name eq "" || $name eq "btnorder"} return

        if {[info exists hidden($name)] && $hidden($name)} {
            set hidden($name) 0
        } else {
            set hidden($name) 1
        }
        apply_order
        refresh_list
        set names [get_sorted_buttons]
        set idx [lsearch $names $name]
        if {$idx >= 0} { .btnorder_dlg.main.list selection set $idx }
    }

    proc refresh_list {} {
        variable hidden
        .btnorder_dlg.main.list delete 0 end
        foreach name [get_sorted_buttons] {
            if {[info exists ::plugin::button_order::button_label($name)]} {
                set label $::plugin::button_order::button_label($name)
                if {[info exists hidden($name)] && $hidden($name)} {
                    set label "* $label"
                }
                .btnorder_dlg.main.list insert end $label
            }
        }
    }

    proc do_save {} {
        variable saved_order
        variable order
        variable hidden
        array unset saved_order
        foreach {name ord} [array get order] {
            set saved_order($name) $ord
        }
        save_config
        tk_messageBox -icon info -title "Порядок кнопок" \
            -message "Порядок кнопок сохранён.\nИзменения вступят после перезапуска."
    }
}

::plugin::button_order::init
